### ISSUE TITLE
Feature request: Implement high pressure cutoff

### ISSUE THREAD

**Issue by colingeniet** [NikolaiVChr/flightgear-saab-ja-37-viggen#101]
The high pressure fuel cock is controlled by the thrust lever, see JA37 english manual sec. 9 (engine) par. 2.2.3.1 and 4.
It is distinct from the low pressure fuel cock controlled by the cutoff switch.

To do:
- [x] Add high pressure cutoff logic
- [x] Implement cutoff catch (and choose which version of the implementation)
- [x] Add flight idle indent
- [x] Review positions of A/B indents (make sure to keep it coherent with A/B zones etc.)
- [x] Update autostart
- [x] Update checklists

**Comment by NikolaiVChr** [comment]
Is that what this image shows, throttle positions vs. engine response:
So either 0-3 deg or 3-9 deg throttle position?

![image](https://user-images.githubusercontent.com/3764194/77805150-8b658600-7081-11ea-8445-7615df2e47f8.png)

**Comment by NikolaiVChr** [comment]
That image is from the "Short RM8A engine description" document. I posted it in discord yesterday.

**Comment by colingeniet** [comment]
Cross checking your picture with JA37 english manual section 9.4:
- 0-3 is the just the stop
- 3-7 is the cutoff position
- 7-9 is the catch for the cutoff position (catch must be lifted to go from idle to cutoff)
- 9-13 is ground idle
- 13-16 is the ident for flight idle (i.e. min power from which the aircraft can quickly spool up)
I would like to add the cutoff zone and indent, and (independently) the flight power ident.

For the cutoff catch, I see two ways: 
- click the throttle to switch from cutoff to idle (sort of like the f16)
- make the cutoff a regular throttle zone, so that the throttle can be pushed normally from cutoff to idle, but you need for instance to click it (to simulate lifting the catch) to go back to cutoff
Which would you prefer?

**Comment by NikolaiVChr** [comment]
Not sure, they both sound good.
I will leave that to you. :)

**Comment by colingeniet** [comment]
By the way the positions of the AB indents on the pictures do not quite match the ones we have (rounded: 70,84,98, versus 70,82.5,95) so I will also change that if you see no issue.

**Comment by NikolaiVChr** [comment]
I see no issue, feel free to improve it.
This is what I modeled what we have now from:

![IMG_0948](https://user-images.githubusercontent.com/3764194/77808554-18add800-708c-11ea-92e5-3b1d7a308c02.JPG)

**Comment by NikolaiVChr** [comment]
I think I took IDLE as 0 and scaled it that way, don't remember.

**Comment by colingeniet** [comment]
Oh, that's perfect with the two together. I mistook the 13-16 zone for the flight idle indent, but it actually is the ground idle catch. I guess 7-9 is the actual cutoff position, but does not have a physical marker on the throttle scale. I should have everything to do it correctly now.

**Comment by NikolaiVChr** [comment]
I could not click on the handle, but change 2 lines in this component and then you can click on handle:

```xml
<switch name="names/fcs/throttle-cutoff-catch">
            <default value="fcs/throttle-cutoff-catch"/>
            <!-- In the cutoff zone, always go back to resting position -->
            <test value="0">
                fcs/throttle-pos-deg-limited lt 13
            </test>
            <!-- If resting and beyond the idle position, engage -->
            <test logic="AND" value="-1">
                fcs/throttle-cutoff-catch == 0
                fcs/throttle-pos-deg-limited ge 15
            </test>
            <!-- If beyond flight idle, do not hold the lifted position.
                 This is purely for gameplay (IRL the lifted position would not hold anyway).
            -->
            <test logic="AND" value="-1">
                fcs/throttle-pos-deg-limited ge 24
            </test>
            <output>fcs/throttle-cutoff-catch</output>
        </switch>
```

Furthermore I can move the throttle in the entire range when it is both below the latch and above it.
Thats not intended is it?

**Comment by NikolaiVChr** [comment]
Plus the launcher states dont work properly after these commits.
