### ISSUE TITLE
Allow AJ(S) to fire weapons without radar lock

### ISSUE THREAD

**Issue by colingeniet** [NikolaiVChr/flightgear-saab-ja-37-viggen#102]
I need to check but it did not seem to work from my quick tests.
If so it should not be too hard since the JA already has that feature.

**Comment by NikolaiVChr** [comment]
Check out line 925 in displayTI.nas, it changes from radar guided lock to fixed lock in middle of hud.

**Comment by colingeniet** [comment]
Thanks for the pointer, I will check that.

**Comment by colingeniet** [comment]
I think I have the IR seeker behaviour reasonably right: it works in boresight mode, and can be uncaged after launch with a button (shift-E).

Now, I would like to do the same with the remaining AJS weapons, namely Rb04, Rb15 and Rb75. I am considering the following:
- make the Rb04 and Rb15 use lock-on after launch, which is closer to their real behaviour
- as a temporary solution, make the Rb75 behave in the same way as IR seekers.

**Comment by colingeniet** [comment]
Oh, I forgot the M90. I have absolutely no idea what to do with that one. It will probably need to wait for a serious AJS radar/navigation rework...

**Comment by colingeniet** [comment]
Rb 04 and Rb 15 done (they fly straight ahead and look for target).

**Comment by colingeniet** [comment]
This is becoming a blocking issue for the AJS HUD rework.
- [ ] M90: The easiest thing I can think of is to make it lock after launch.
This is throwing realism out of the window, but is easy to understand and to implement, and works the same way as the Rb 04 and Rb 15, so I think it is a good solution until navigation systems and CI are advanced enough to set a target waypoint.
- [ ] Rb 75: Make a HUD marker for the seeker position. Seeker can be moved with radar cursor controls (this is accurate), and 'clicking' locks on a target.

**Comment by colingeniet** [comment]
Fixed in barnch `hud-rework`.
