### ISSUE TITLE
AJS waypoint bearing indicator sometimes locks up

### ISSUE THREAD

**Issue by colingeniet** [NikolaiVChr/flightgear-saab-ja-37-viggen#103]
The waypoint indicator around the AJS radar screen sometimes stops working (stuck on straight ahead position).

**Comment by NikolaiVChr** [comment]
I dont remember where this code is.

**Comment by colingeniet** [comment]
It's mostly in `jsb-flight.xml`, but there is a part of it in `ja37.nas`. I sort of fixed it, but I still think there are some issues with it:
- The nasal part makes it laggy, it should be simple to remove.
- If you turn a lot in the same direction, the compass will at some point turn in the reverse direction, as if there was a gimbal lock. I don't think that it is intended, but I am not sure.

**Comment by NikolaiVChr** [comment]
In next FG version there will be some JSB changes for cyclic properties that will make this easier to make I believe.

**Comment by colingeniet** [comment]
Fixed by https://github.com/NikolaiVChr/flightgear-saab-ja-37-viggen/commit/7911cfecc60145cf61e9fa4804653cb0843711fb and https://github.com/NikolaiVChr/flightgear-saab-ja-37-viggen/commit/2e46ef61eb6166c411d712f940758a7d80fcf3d2. I used property-rules instead of JSB for the cyclic properties, to avoid compatibility issues with older FG versions.
