### ISSUE TITLE
Gun sight

### ISSUE THREAD

**Issue by NikolaiVChr** [NikolaiVChr/flightgear-saab-ja-37-viggen#104]
I think just making a segmented circle will probably do. And then only show it for radar locked targets.

This is the only information we have about how the gun sight looks like:

![IMG_0241](https://user-images.githubusercontent.com/3764194/77804272-6c65f480-707f-11ea-9352-2b0063159f75.JPG)

**Comment by NikolaiVChr** [comment]
Okay it should now work: 259ee94c5379c0a1ef18c6dac647f0684b388f2

It will appear if target is radar locked and approx less than 1 mile out.

**Comment by colingeniet** [comment]
Shouldn't the centre point on the picture be part of the sight?

**Comment by NikolaiVChr** [comment]
Maybe, I dont know what it is.

It might be the velocity vector, not sure, but it is not shown same place as the radar lock symbol, so not sure.

**Comment by NikolaiVChr** [comment]
It *might* be a line from bore-cross to the sight, hard to tell.
