### ISSUE TITLE
Realistic radar

### ISSUE THREAD

**Issue by colingeniet** [NikolaiVChr/flightgear-saab-ja-37-viggen#105]
There are essentially two distinct issues, for the two models:
- The JA has (I think?) an air radar, so it should not display ground contacts. It's basically already done in `radar-logic.nas` (even a nice doppler radar simulation), just not activated.
Since radar lock is no longer required for gun/rocket, I see no issue in just not displaying ground targets anymore.
- For the AJS I don't know (since it's a ground radar). I need to read the documentation to understand how it actually works. If you know some details about how it, I would be interested, it would limit the amount of google translate from Swedish I have to do.

**Comment by NikolaiVChr** [comment]
Its been a long time since I read the AJ parts about radar. Sorry.

**Comment by vanosten** [comment]
Radar panel picture: https://digitaltmuseum.se/011023011883/radarpanel and https://digitaltmuseum.se/011023011873/radarpanel
