### ISSUE TITLE
Texture of b/90 should have yellow stripe instead of green

### ISSUE THREAD

**Issue by vanosten** [NikolaiVChr/flightgear-saab-ja-37-viggen#112]
Green stripe means weapon for siluation, green total means dumb weapon. The stripe should be yellow.

Could only find a picture in https://thaimilitaryandasianregion.wordpress.com/2017/04/27/gripen-multirole-fighter-aircraft/ (you need to scroll down quite a bit).

**Comment by vanosten** [comment]
A photo of a s/90 simulate with green stripe: https://digitaltmuseum.se/011023032147/bombkapsel

**Comment by vanosten** [comment]
https://www.aef.se/Flygvapnet/Tidskrifter/FV_Nytt/Flygvapennytt_1991-5.pdf has a detailed description as well as more pictures regarding its form

**Comment by colingeniet** [comment]
Fixed, gave it the same colour as the M71.
