### ISSUE TITLE
AJS: Make the Rb05A guidance based on pilot input instead of calculated flight path

### ISSUE THREAD

**Issue by vanosten** [NikolaiVChr/flightgear-saab-ja-37-viggen#113]
Currently you need to lock a target with the radar and then shoot fire and forget. However, that is not how it is guided in real life.

- https://www.aef.se/Flygvapnet/Tidskrifter/FV_Nytt/Flygvapennytt_1972-4.pdf has an article on page 24 about it.
- Fpl AJS 37 speciell förarinstruktion (SFI) del 1.pdf, page 440 ff.
- Fpl AJS 37 speciell förarinstruktion (SFI) del 3.pdf, page 210 ff.

**Comment by NikolaiVChr** [comment]
Yes but is not trivial to make, and will be next to impossible to get it to hit anything with pilot input in FG.

**Comment by vanosten** [comment]
Fpl AJS 37 .. del 2.pdf, page 86: with right hand use the mini-joystik to guide the weapon, with left left hand take the stick and fly the airplane.

**Comment by vanosten** [comment]
At around 14:02:14:12 in https://www.youtube.com/watch?v=RHVzkVwI68w a pilot can be seen firing a Rb05A and guiding it. also visible is the collimated light at the missile's back

**Comment by NikolaiVChr** [comment]
I checked this branch, its very neatly done.

However this:
m.remote_yaw_path
m.remote_pitch_path

Is not needed, right?

**Comment by colingeniet** [comment]
Merged, and slightly improved the performance to better match the graph in the Rb05 description in the AJ37 SFI part 2.
Initial acceleration is much higher, for a launch at M0.75, maximum speed of M1.5 is reached after 5s. I made it a false 2-stage engine to simulate decrease in thrust.
