### ISSUE TITLE
Simplify option menu(s)

### ISSUE THREAD

**Issue by colingeniet** [NikolaiVChr/flightgear-saab-ja-37-viggen#118]
I propose the following changes to the option menus:
- Remove the FCS gearing/limiter/damping options. I don't think that they are supposed to be disabled on the real aircraft.
- Replace the buttons with checkboxes and sliders as appropriate, to make the UI easier to use.
- Merge the MP option menu with the main option menu.

On the technical side, is there a reason to keep the main option menu generated by `Nasal/options.nas`, instead of an xml dialog? I think the latter would be just as good and simpler.

**Comment by NikolaiVChr** [comment]
No reason, no.

**Comment by colingeniet** [comment]
I changed the menu as described, please tell me if you have any issue with the new one.
