### ISSUE TITLE
DC dies and AC lies

### ISSUE THREAD

**Issue by NikolaiVChr** [NikolaiVChr/flightgear-saab-ja-37-viggen#119]
@colingeniet Since you are reworking the gauges, maybe you could check that that is consistent in all the gauges.

DC dies: DC powered gauges goes to zero when power is off.
AC lies: AC powered gauges freeze when they lose power.

**Comment by colingeniet** [comment]
Thank very much you, I did some instrument logic rework, but did not know that. Out of curiosity, is there a technical reason for it?

For several flight instruments, the SFI (part 1) only states that they 'are servo-actuated and use signals from the air data computer' (main altimeter, mach indicator...).
My guess would be that they fall in the AC category, but do you know more?

**Comment by NikolaiVChr** [comment]
I only know he ones in this diagram, I think I kinda just assumed whats not mentioned here is AC:

![image](https://user-images.githubusercontent.com/3764194/79496618-ac891900-8026-11ea-819e-2409deb39e93.png)
