### ISSUE TITLE
Fix shaders with Compositor (again)

### ISSUE THREAD

**Issue by colingeniet** [NikolaiVChr/flightgear-saab-ja-37-viggen#122]
The following is all using the `compositor` branch rebased on `master`, and a recent (april 2020) compositor build. The `default` compositor pipeline works fine.

With the `als` pipeline, I get this:
![fgfs-20200423091105](https://user-images.githubusercontent.com/23284595/80082002-ff496000-8553-11ea-955d-4737e48522ae.png)
![fgfs-20200423091114](https://user-images.githubusercontent.com/23284595/80082004-ffe1f680-8553-11ea-9068-ba01acd6fb72.png)

But it get interesting when tilting the camera up:
![fgfs-20200423091205](https://user-images.githubusercontent.com/23284595/80082049-12f4c680-8554-11ea-9d85-2ce434e25adb.png)

It seems the shaders are not completely broken (as in they are rendering something).
Notice how in the last picture the hull is a bit transparent, and fades away when the clouds are behind. It looks like the aircraft is rendered in the background, so probably something broken with z-values?

**Comment by colingeniet** [comment]
Forgot to mention, of course I did not get any error message in the console, or I would have posted it.

**Comment by colingeniet** [comment]
After 5 minutes of research, it obviously is a z-buffer issue, since Compositor was changed to use logarithmic z-buffer in shaders.

**Comment by NikolaiVChr** [comment]
I will fix that when 2020.1.1 comes out.

**Comment by colingeniet** [comment]
Fixed the logarithmic depth in branch `compositor2`.
Now the real problems become visible:
![fgfs-20200430082511](https://user-images.githubusercontent.com/23284595/80689157-2a403080-8acd-11ea-8c89-ecbd4b6b06d1.png)

**Comment by colingeniet** [comment]
To fix:
- [ ] The 'black checkerboard' is caused by the external lights. It disappears when turning them off.
- [ ] As far as I understand, using `/sim/rendering/shaders/skydome` to test if ALS is enabled is not correct with Compositor. 
In the effect files, it seems like the test can simply be removed from the `<predicate>`, the correct shaders will be used if they are marked with `<scheme>als-lighting</scheme>`. However there are also tests in the model `.xml` files which need to be replaced.
- [ ] Fuselage shader depth buffer is broken with low-spec pipeline and model shaders off.
- [ ] Display shader depth buffer is broken with ALS pipeline and model shaders off.
- [ ] The fuselage is way to white (with ALS pipeline and model shaders on)

To insist, tests are required with at least every combination of the following parameters:
- Compositor pipeline default/ALS
- Model shaders on/off

**Comment by NikolaiVChr** [comment]
What external lights? landing/taxi or the others?

/sim/rendering/shaders/skydome will probably be fixed by Icecode so it can be used again. Think its a bug that it cant be used now.

Fuselage shader needs reordering of techniques, since model-combined was reordered.

**Comment by colingeniet** [comment]
> What external lights? landing/taxi or the others?

Only landing/taxi indeed

> /sim/rendering/shaders/skydome will probably be fixed

Good to know. It should be tied to the pipeline used by the compositor?

> Fuselage shader needs reordering of techniques, since model-combined was reordered.

Thanks, this fixes the fuselage being broken on low-spec with shaders off.
I will check if other inherited effects need the same.

**Comment by colingeniet** [comment]
> Gamma correction is done higher up in the file now. With this line it appears you do gamma correction twice.

That sure didn't help. I blame `git rebase` for the duplication, and myself for not checking the diff.

**Comment by colingeniet** [comment]
Closing as it is no longer relevant. Compositor is now merged on next, and has very good backward compatibility.
Also it currently does not include clustered shading, which was the source of the checkerboard issue.

The only changes that will be needed is to add shadows to the fuselage shader.
