### ISSUE TITLE
Redundant shaders

### ISSUE THREAD

**Issue by colingeniet** [NikolaiVChr/flightgear-saab-ja-37-viggen#123]
Since the shaders need to be ported to Compositor/debugged (#122), I am very much interested in reducing the number of custom shaders which we have.

Many of the shaders we have (e.g. `noise.frag`, `glass-ALS.{vert,frag}`) are identical to the ones in fgdata. Is there any issue with removing these?

**Comment by NikolaiVChr** [comment]
They are there because I wanted the effects before the official release in FG.

So no should be fine to remove.

But not the thrust effect, its modified, so that that it shows heatblur.

**Comment by colingeniet** [comment]
> They are there because I wanted the effects before the official release in FG.
That's more or less what I suspected, thanks for confirming.

I will make sure to keep `thrusthead-ALS.{frag,vert}`. 
What about the shaders under `Models/Effects/fuselage`, and `displays/lcd.{frag,vert}` ? Are they modified versions?
Everything else seems to be duplicate.

**Comment by NikolaiVChr** [comment]
fuselage and display are my shaders.

fuselage is a heavy modified model-combined
display is a shader I made from scratch

**Comment by NikolaiVChr** [comment]
As for the other shader beside those 3 I dont remember if I made changes.
Will just have to diff them.

**Comment by colingeniet** [comment]
Yes, I just checked, there are no differences for the others.

**Comment by colingeniet** [comment]
Correction, the ALS lights shader also has some changes.

**Comment by NikolaiVChr** [comment]
Oh yeah, I made that work in non-als.
