### ISSUE TITLE
Missile coloration

### ISSUE THREAD

**Issue by l0k1** [NikolaiVChr/flightgear-saab-ja-37-viggen#13]
Looks like the missiles are textured wrong?

Info taken from various searches, most info on coloration is from forum posts etc, but the best  summation is: http://www.ipmsstockholm.se/phpBB3/viewtopic.php?t=1880.

From what I can tell, non-homing, no warhead "dummy" missiles were all green; homing, no warhead missiles "training" missiles were green with a white head; and regular missiles were grey with a yellow band. 

I've done several searches through english and swedish channels, and the results are consistent with this coloration.

**Comment by NikolaiVChr** [comment]
Awesome find. Will look better with grey missiles anyway. :)
I will do that in the coming days, or when I find time.

**Comment by NikolaiVChr** [comment]
#14 fixed this.
