### ISSUE TITLE
Disable Rb05 flare / M71R chute when jettisoning.

### ISSUE THREAD

**Issue by colingeniet** [NikolaiVChr/flightgear-saab-ja-37-viggen#135]
For `missile.nas`, jettisoning is just firing with no engine.
However some missile animation needs to be different when jettisoning.

This will probably require to add a new property flag in `missile.nas`, waiting for emesary merge before fixing it to avoid a mess.

**Comment by NikolaiVChr** [comment]
If this relies on deploy then it should be fixed in f16 emesary branch.

**Comment by colingeniet** [comment]
Fixed the animation in branch emesary by using `deploy-id-*`.
