### ISSUE TITLE
Rb05 creates crater even if exploding in the air

### ISSUE THREAD

**Issue by colingeniet** [NikolaiVChr/flightgear-saab-ja-37-viggen#136]
A crater will appear on the ground, vertically below the point of explosion.

It likely is a generic issue in `missire.nas`, not something specific to the Rb05.
Waiting for emesary merge before fixing it to avoid a mess.

**Comment by NikolaiVChr** [comment]
This has been fixed in F16, thought it was easier to just fix it in emesary branch.

**Comment by colingeniet** [comment]
Fixed by porting the F16 changes on branch emesary.
