### ISSUE TITLE
delta-drag-coeff-deploy breaks CCIP

### ISSUE THREAD

**Issue by colingeniet** [NikolaiVChr/flightgear-saab-ja-37-viggen#137]
In `missile.nas`, the parameter `delta-drag-coeff-deploy` is perfect to simulate the M71R drag chute deploying.
However CCIP only uses the base drag coefficient.

**Comment by NikolaiVChr** [comment]
https://github.com/NikolaiVChr/f16/commit/3bcb601db85d2b995443eb3d039921360d0e535d

**Comment by colingeniet** [comment]
Thank you
