### ISSUE TITLE
m71 retarded parachute fold out time

### ISSUE THREAD

**Issue by NikolaiVChr** [NikolaiVChr/flightgear-saab-ja-37-viggen#139]
`<deploy-time>` is listed twice with 2 different values.

Drop-time is missing, it should be 0.8s  (SFI del 1 1996 chapter 25 page 25)

This is the drop order btw:
![image](https://user-images.githubusercontent.com/3764194/97779653-bb2cbd00-1b7f-11eb-9b4a-84c7c893f4f9.png)

**Comment by colingeniet** [comment]
Fixed `deploy-time` and `drop-time`.
I have the drop order from this figure, yes.
