### ISSUE TITLE
MI improvements

### ISSUE THREAD

**Issue by colingeniet** [NikolaiVChr/flightgear-saab-ja-37-viggen#141]
I would like to remove the 'select next target' shortcut, which is particularly unrealistic.
Before doing so, there are a couple of changes I want to make to the MI to make it easier to use for target selection.
- [x] Make the MI a B-scope display.
- [x] Improve cursor refresh rate.
- [x] Make the target numerical information at the top bigger---I find it hard to read currently. Also maybe remove the closure rate (ÖKA/AVTA) information?
- [x] Add velocity vector of target on the screen.
- [x] Optionally, change symbol for selected target, see below.

For the most part, my source is https://www.youtube.com/watch?v=kBq5qA8r4dA at 13:01
Very interesting extract IMO:
- It shows a selected target (the '#'). On top, the target speed, distance, altitude. (We already have it, but it's too small).
- The presentation matches perfectly with a B-scope: the target is at ~20km and closing (read against the left scale), which matches the A21 and decreasing displayed on top.
- The dash below the target looks like a velocity vector.

**Comment by NikolaiVChr** [comment]
Yep, you are right, its a B-scope:
![image](https://user-images.githubusercontent.com/3764194/97789623-357e3100-1bc2-11eb-9719-9258b01b5af9.png)

I am pretty sure the closure info is as it should be. I tried to find where I got that info from, but only found these:

![image](https://user-images.githubusercontent.com/3764194/97789660-91e15080-1bc2-11eb-97be-589365ad3f2b.png)
![image](https://user-images.githubusercontent.com/3764194/97789715-dec52700-1bc2-11eb-8a52-02c9a8ec40f2.png)
![image](https://user-images.githubusercontent.com/3764194/97789933-afafb500-1bc4-11eb-94c0-b3cd08f4652b.png)

**Comment by NikolaiVChr** [comment]
Ah, found at least one pic with it:

![image](https://user-images.githubusercontent.com/3764194/97790185-c0612a80-1bc6-11eb-8a18-daf240dfe9f4.png)

**Comment by colingeniet** [comment]
Here's the symbols I understand with these additional pictures:
- # Is the target symbol.
- the circle looks like a target from datalink/fighter control?
- the big cross looks like a good candidate for a cursor.
- I have no idea what the big dot means.
- horizontal lines on top/bottom indicate radar sweep range.
- on the altitude scale there is a vertical bar (~5km to 10km on the 4th image). I suspect it might indicate vertical range of the radar.

I think your images mostly show TWS mode, while my video shows STT (the radar sweep indicator in the video seems to be just the vertical bar).

**Comment by colingeniet** [comment]
Here's the result for now:
![fgfs-20201103215603](https://user-images.githubusercontent.com/23284595/98045452-d8d07f80-1e28-11eb-94c1-b1845d4a1621.png)

I think I managed to display almost every functionality at once.
Bottom left text will display either the QFE warning, or the selected weapon, or the Mach number.
To do:
- [ ] Restore Rb 99 telemetry. Maybe sharing the same position as the buttons help?
- [ ] Cursor controlling Rb 74 seeker head doesn't work anymore. Need to update seeker logic accordingly.
In particular, Rb 74 can not be used with radar off without going into the TI configuration.

Other ideas?
