### ISSUE TITLE
Model shader

### ISSUE THREAD

**Issue by colingeniet** [NikolaiVChr/flightgear-saab-ja-37-viggen#146]
I'm trying to understand what the effect `model-combined-fuselage.eff` does, that is what are the differences with the FGData shaders it is based on. I'd like to as many custom shaders as possible, to make it simpler to maintain them, notably with FG Compositor addition.

For reference correspondence with FGData files is as follows:
- `Effects/fuselage/model-combined-fuselage.eff` -> `Effects/model-combined.eff`
(but I think `Effects/model-combined-deferred` should be used for inheritance).
- `Effects/fuselage/model-combined-fuselage.{vert,frag}` -> `Shaders/ubershader.{vert,frag}` (non-ALS pipeline)
- `Effects/fuselage/model-combined-fuselage-ALS.{vert,frag}` -> `Shaders/model-ALS-ultra.{vert,frag}` (ALS pipeline)

Changes from FGData for the non-ALS pipeline:
- Support for BC3N DDS compression for normal map.
  I am considering reverting the normal map to PNG:
  * PNG compression is really nice for a normal map (220Kb PNG vs 5.4Mb DDS).
  * FG now has a DDS cache anyway, so having to decompress the PNG is not an issue.
- Inverted the meaning of parameter `<ambient-factor>`. Why?
- A fix to light map when `lightmap-multi` is off: the light map texture is multiplied by its red component.
  This seems like a bug in FGData shaders indeed. Why was the fix not sent to upstream?
  (remark: I think the bug can also be worked around by enabling `lightmap-multi`)
- Some visual changes (fog, low light conditions).
  Since this is the low quality pipeline, which is not supposed to look particularly good,
  it seems reasonable to me to remove them for the sake of using upsteam shader.
  If the changes are really justified, they we should submit them to upstream.

Thus, regarding the non-ALS pipeline, I think we can revert to FGData shaders after doing the following:
- [ ] Change normal map to PNG, or a DDS format compatible with FGData shader.
- [ ] Revert `ambient-factor` to its original meaning.
- [ ] Clarify light map situation, send fix upstream, and possibly add workaround.

I will look at the ALS pipeline after that.

**Comment by NikolaiVChr** [comment]
`ambient-factor` does not exist in fgdata. Its used to control the ambient occlusion map, which also does not exist in fgdata.
The reason for using that special DDS compression of the normal map, is to remove ugly artifacts that you get with PNG and normal DDS.
fgdata has really bad low-light and moon light, this shader takes care of that.
fgdata has 2 specular spots even during daytime, its wildly unrealistic and look really bad.
The reflection map blending is done not good in fgdata, its much better in this shader, and removes the need for `<ambient-correction>` parameter.
fgdata does not have metallic specular spots, this shader has.
