### ISSUE TITLE
Beacon illuminating objects that should be blocked (compositor-master)

### ISSUE THREAD

**Issue by ZorkaA** [NikolaiVChr/flightgear-saab-ja-37-viggen#156]
Engine intakes, ordnance is being illuminated by the beacon on top of the aircraft.

**Comment by colingeniet** [comment]
I'll make the top / bottom beacon light point a bit more up / down respectively to make the issue less visible.

I don't think I can do much more. Compositor lights don't have shadows, that would be way too costly.

**Comment by colingeniet** [comment]
It should be better now
