### ISSUE TITLE
View position

### ISSUE THREAD

**Issue by colingeniet** [NikolaiVChr/flightgear-saab-ja-37-viggen#158]
- [ ] The shake effect / seat position script constantly writes to `sim/current-view/y-offset-m`. This is a  problem if anything else (e.g. headtracking) tries to do the same simultaneously. I think we should avoid such code in an aircraft.
  - [x] Seat position can be easily rewritten without this (only write to `y-offset-m` when actually changing seat position).
  - [ ] Shake effect is harder. ~~I need to look at the new generic shaking in 2020.4.~~ It won't do, it is designed for ground roll wobbling, not buffeting.
- [x] I think the default view position should be moved a bit backward (~10-20cm), with lower FOV (~80°). The problem would be HUD visibility at high AoA.

**Comment by NikolaiVChr** [comment]
I found it hard to find a good compromise on how to set the view.
The reason I placed it so close was to get the HUD to fill up more of the view, in real life the brain can sorta focus on a part of where the eyes are looking, while on a monitor if its small it can get hard to focus and read the HUD.
The reason the view was so wide was to have MI, TI and HUD all in the default view without having to move it, as most people do not have head-tracker.

**Comment by colingeniet** [comment]
> The reason I placed it so close was to get the HUD to fill up more of the view, in real life the brain can sorta focus on a part of where the eyes are looking, while on a monitor if its small it can get hard to focus and read the HUD.

As far as HUD readability goes, it can only get better with lower FOV. I guess the issue is how much of the HUD picture is visible.
I understand that what is displayed right now is less than what the two eyes combined would see.
On the other hand what is displayed is definitively more than what a single eye would see.

> The reason the view was so wide was to have MI, TI and HUD all in the default view without having to move it, as most people do not have head-tracker.

All the screens are still visible in the default view (with 16:9 ratio).

**Comment by NikolaiVChr** [comment]
> All the screens are still visible in the default view (with 16:9 ratio).

Nice

**Comment by NikolaiVChr** [comment]
Oh, I now rembered another reason I moved it so front.
To have better view down the nose so could see the touchdown point when landing with higher AoA.
If I moved the eye back then I had to raise it to see which was a no no, since I then no longer had the HUD bore cross in the HUD.

**Comment by colingeniet** [comment]
Regarding the head shaking issue, I think it is best to add an option to disable it (like the MiG-21).

**Comment by colingeniet** [comment]
Added an option to disable head shaking.
Improved the seat movement code, so that it can work with this option enabled or not.
