### ISSUE TITLE
Last Maverick does not shut down the seeker

### ISSUE THREAD

**Issue by vanosten** [NikolaiVChr/flightgear-saab-ja-37-viggen#171]
On win 10 with latest FG next and latest Viggen AJS. When having loaded 4 Mavericks: saving the trigger after firing the weapon correctly shuts down the mode in the HUD and the grey texture in the seeker - for the first 3 Mavericks. After the 4th the HUD mode switches back after saving the trigger, but the grey texture in the seeker remains.

**Comment by colingeniet** [comment]
Fixed by https://github.com/NikolaiVChr/flightgear-saab-ja-37-viggen/commit/b363088390124b1663e66e0925db7f45dc39ea3e
