### ISSUE TITLE
Please extract folder

### ISSUE THREAD

**Issue by sidardeha** [NikolaiVChr/flightgear-saab-ja-37-viggen#178]
Please extract folder because if I extract it by myself I won't be able to update it with "git pull"

**Comment by SammySkycrafts** [comment]
All you need to do is add the folder that you downloaded to FG. then you just need to do git pull. You can see how i do it in the screenshot below:
![image](https://user-images.githubusercontent.com/77464976/169670807-ce614751-01e1-463a-b657-87eafe8daab0.png)

**Comment by colingeniet** [comment]
I see where you're coming from, but there's no way I'm moving the repository root directory, sorry.
It messes up `git log <file>` history, it's a recipe to accidentally delete out-of-tree files when checking out old versions, etc. Too many issues to justify the change.

You can do as Sammy suggests, or simply add a symlink:
`Aircraft/JA37 -> Aircraft/flightgear-saab-ja-37-viggen/Aircraft/JA37`.

**Comment by sidardeha** [comment]
Okay, thanks.
