### ISSUE TITLE
Altimiter 3 is a distance indicator

### ISSUE THREAD

**Issue by l0k1** [NikolaiVChr/flightgear-saab-ja-37-viggen#18]
Hey!
Referencing part 1 of the AJS-37 manual, section 24 on navigation, subsection 2.4 (page 346 in the PDF), it looks like what you have as Altimeter 3 should actually be the Avstandsindikator, or distance indicator, and is toggleable between KM and miles (selected unit of measure is displayed on the gauge).

Bad google translate of the section:
The range indicator shows how close to the destination that is shown on the destination indicator. The indicator has two distance ranges; 0-40 km and 0-40 mil. Exchange of distance range takes place at 40 km respective mil displayed in a window on the indicator.

**Comment by NikolaiVChr** [comment]
OMG, how could i miss that. I did wonder why there was 3 altimeters.

**Comment by l0k1** [comment]
Haha yeah. I was wondering why there was one that went up to 40km! Initially I was like "Whoa, the service ceiling on this plane must be ridiculous."

**Comment by NikolaiVChr** [comment]
hehe.

So since you were looking into some navigation stuff anyway, will you look at it, or shall I?

If I fix it, I probably wont include the option to show miles, since I am not so good with blender.

I guess it should show distance to next steerpoint, unless DME is active then it should probably show that. Will check the manual on that.

**Comment by l0k1** [comment]
Per the AJS-37 manual, the DME switch "has no function". =] (not going to disable it haha, I use it way too much and it doesn't hurt anything)
And it shows the distance to whatever item is on the destination indicator, which is those two letters where you have the drop tank indicator now. 
Honestly, though, I agree with your approach to keep it simple for the regular user. Next waypoint in route manager, or DME if DME is active.

**Comment by l0k1** [comment]
Also, yeah I can implement it no prob. Should be relatively easy if we just do km.
