### ISSUE TITLE
3D model is see-through from behind

### ISSUE THREAD

**Issue by l0k1** [NikolaiVChr/flightgear-saab-ja-37-viggen#26]
looking between the reverser outlet and the main body of the aircraft, you can see through.
![fgfs-screen-009](https://cloud.githubusercontent.com/assets/1434407/13661222/b02054d6-e645-11e5-990f-4ff0f23f5703.png)

**Comment by NikolaiVChr** [comment]
Yes, that is a great shame on the aircraft.
I will see if I can fix it before "2016.2.1 Barcelona".

**Comment by NikolaiVChr** [comment]
Fixed.
