### ISSUE TITLE
HUD crashes

### ISSUE THREAD

**Issue by l0k1** [NikolaiVChr/flightgear-saab-ja-37-viggen#27]
Hey,
Looks like this has something to do with the route manager.
I had loaded a route from xml, and then selected an arrival runway (at KCHS - runway 15), when the hud crashed. This may have crashed prior to this, however. Error is:

command 'nasal' failed with exception
        message:invalid leg index (from FlightPlan::setCurrentIndex)
Nasal runtime error: unterminated index (looking for ']')
  at C:/Users/soweli/Documents/FlightGear/ja-37/Aircraft/JA37/Nasal/hud.nas, line 1591
  called from: C:/Users/soweli/Documents/FlightGear/ja-37/Aircraft/JA37/Nasal/hud.nas, line 1035
  called from: C:/Users/soweli/Documents/FlightGear/ja-37/Aircraft/JA37/Nasal/hud.nas, line 1064

**Comment by l0k1** [comment]
Also, the circle on the radar marking a waypoint doesn't work, and the distance to waypoint doesn't work.

**Comment by l0k1** [comment]
Actually, part of the route manager crashed too. This may be 100% related to the route manager.

**Comment by NikolaiVChr** [comment]
Just in case this happens again, I have put in a check that should prevent the HUD crashing when the route-manager does. Hope that solves your problem.

**Comment by NikolaiVChr** [comment]
I am going to close this for now, reopen if the issue pops up again.
