### ISSUE TITLE
KCA impact report not working

### ISSUE THREAD

**Issue by l0k1** [NikolaiVChr/flightgear-saab-ja-37-viggen#32]
Getting the following report in the console:

`Nasal runtime error: No such member: get_Coord
  at C:/Users/soweli/Documents/FlightGear/ja-37/Aircraft/JA37/Nasal/stores.nas, line 454
  called from: C:/Program Files/FlightGear 2016.2.0/data/Nasal/globals.nas, line 119`

This happens 100% of the time currently.

**Comment by NikolaiVChr** [comment]
Should be fixed now.
