### ISSUE TITLE
Model the Gunpod between the belly and the Drop-tank

### ISSUE THREAD

**Issue by NikolaiVChr** [NikolaiVChr/flightgear-saab-ja-37-viggen#35]
The JA-37 has a gunpod under the belly. Right now its modelled as AJ-37 without the gunpod.

@l0k1 has started looking into this.

![gunpod](http://s19.postimg.org/dop6noecj/cannon.jpg)

![gunpod](http://s19.postimg.org/81stq7btv/detail_viggen_14_557x230.jpg)

![gunpod](http://s19.postimg.org/r0mzam6qr/viggen_25.jpg)

**Comment by l0k1** [comment]
This is solved, I think?

**Comment by NikolaiVChr** [comment]
@l0k1 Has fixed this, closing.
