### ISSUE TITLE
Reverse outlet door

### ISSUE THREAD

**Issue by NikolaiVChr** [NikolaiVChr/flightgear-saab-ja-37-viggen#50]
This outlet closes above certain speed to reduce drag, its a ring that moves forward:

![37_reverser_outlet_door](https://cloud.githubusercontent.com/assets/3764194/16793914/d6987f5c-48d4-11e6-968e-cb9953ac6180.png)

**Comment by l0k1** [comment]
![asdf](http://i.imgur.com/t9Kkt8h.jpg)

I can break it into a bunch of pieces like the outlet nozzle, so that this is possible.

**Comment by NikolaiVChr** [comment]
Pinto made this.
