### ISSUE TITLE
Speed indication switches to international above 600 km/h

### ISSUE THREAD

**Issue by vanosten** [NikolaiVChr/flightgear-saab-ja-37-viggen#62]
At least in the AJS (Windows 10, FG next - but also seen in other versions) the speed indication in the HUD switches automatically to KT as soon as the speed is above 600 km/h. When the speed gets below 600 km/h again, then the speed indication also moves back from KT to km/h. The analog instrument on the left side constantly shows the right speed in km/h and the mach indication in the HUD also is correct all the time.

**Comment by NikolaiVChr** [comment]
Is your Viggen set to metric or Imperial?

What does the HUD say? Does it look like "550", "KT550" or "GS550"?

**Comment by vanosten** [comment]
I run in metric. In "Options" I have "Custom JA 37 specific HUD" = enabled (I guess that is also correct for the AJS as otherwise the HUD is gone). I have uploaded a bunch of screenshots at https://my.pcloud.com/publink/show?code=kZx8Kg7ZeJIiuAeOsfy93tq7tLfych5fA3fX. The switch happens at around 610-620 km/h. And it happens both when having master arm on ("GS550") and if it is off ("550"). It never shows "KT550"

**Comment by NikolaiVChr** [comment]
Fixed.
