### ISSUE TITLE
FG freezes, and says "Fatal exception. Bad conversion"

### ISSUE THREAD

**Issue by NikolaiVChr** [NikolaiVChr/flightgear-saab-ja-37-viggen#63]
Report from JA37Di:

> When i start in parking state (all systems off), following pre-flight checklist 1 and 2, everything works fine. Until I switch on "Main electricity"! Then FG freezes, and says "Fatal exception. Bad conversion" !

Windows 10, FG 2018.2.2

Version 4.312/4.313

**Comment by NikolaiVChr** [comment]
Also in FG 2018.3.1 all his planes give this error, so he reinstalled 2018.2.2.
He also tried deleting $FG_HOME made no difference.

**Comment by NikolaiVChr** [comment]
This is a Flightgear issue with Windows Users that have 'øæåöä' characters in the name.

See discussion [here.](https://forum.flightgear.org/viewtopic.php?f=22&t=34143)

**Comment by it0uchpods** [comment]
Perhaps then this isn't a Viggen issue?

**Comment by NikolaiVChr** [comment]
Indeed its not, its a FG issue.

A workaround can be found in the discussion link above.
