### ISSUE TITLE
Possible that the new cutoff broke inverted flying

### ISSUE THREAD

**Issue by NikolaiVChr** [NikolaiVChr/flightgear-saab-ja-37-viggen#70]
The new cutoff might have broken that flying inverted for too long should make engine starve of fuel.

Will confirm once I get time.

**Comment by colingeniet** [comment]
I think it still works correctly, my engine certainly dies in inverted flight.

The oil pressure test in `cutoff-actual` (which I think is responsible of this effect) is still here:
```systems/flight/oil/pressure-drop-norm lt 0.5625```

**Comment by NikolaiVChr** [comment]
thanks for confirming this, I hadnt gotten around to it.
