### ISSUE TITLE
New FCS and A/P

### ISSUE THREAD

**Issue by NikolaiVChr** [NikolaiVChr/flightgear-saab-ja-37-viggen#75]
Josh has been making this.

This issue is for remaining issues around it.

List:
ja37/avionics/high-alpha has been moved to autopilot although its a property used not only for A/P. I suspect code is broken several places due to this.

I don't understand autoflight/mw-reset, I need to.

A/P light on right warning indicator panel should be updated. See next post.

**Comment by NikolaiVChr** [comment]
![image](https://user-images.githubusercontent.com/3764194/63581114-9067d180-c596-11e9-9b54-5e03dd714ca2.png)
![image](https://user-images.githubusercontent.com/3764194/63581210-c907ab00-c596-11e9-8163-307c298067cb.png)
![image](https://user-images.githubusercontent.com/3764194/63581335-171cae80-c597-11e9-90ae-dce06c8e493d.png)
![image](https://user-images.githubusercontent.com/3764194/63581652-dbceaf80-c597-11e9-863a-7b47ccd6bb84.png)
![image](https://user-images.githubusercontent.com/3764194/63581720-f86ae780-c597-11e9-801d-d6c738ce6c22.png)

**Comment by NikolaiVChr** [comment]
Need the following properties from A/P system:

In some conditions the A/P should make desired pitch lines in HUD and CI blink. Plus red light on CI/TI. Need the property for that.

ATT mode engaged
ALT mode engaged
SPAK mode engaged
Loss of AC for more than 2s
Loss of AC for more than 6s
Loss of DC for more than 6s
Autothrottle is in mode 1 (speed HOLD)
Autothrottle engaged
Manual yaw trimming in flight
Pitch trim malfunction (if available)
Pitch or roll standby trimming?
Transonic for more than 60s
Pitch gearing switch if it was changed

A/P altitude target difference to altitude less than 50 meters + 1.8% engage altitude:
  if (alt_meters - AP_target_alt_meters < -(50 + 0.018 * AP_target_alt_meters))
    blink ground-collision lights

**Comment by NikolaiVChr** [comment]
Okay the property for temp mode where lines blink is:
/fdm/jsbsim/autoflight/temp-mode-active

**Comment by Octal450** [comment]
Here, some things: (all /fdm/jsbsim/ unless I put a leading /)
ATT mode engaged: autoflight/mode eq 2
ALT mode engaged: autoflight/mode eq 3
SPAK mode engaged: autoflight/mode eq 1
Autothrottle is in mode 1 (speed HOLD): autoflight/athr-mode ne 1
Autothrottle engaged: autoflight/athr eq 1
Manual yaw trimming in flight: abs(/controls/flight/rudder-trim) >= 0.02
Transonic for more than 60s: autoflight/alt-transonic-timer eq 1
Pitch gearing switch if it was changed: fcs/elevator/gearing-enable

Can get you more once I get them properly.

Kind Regards,
Josh

**Comment by NikolaiVChr** [comment]
Does this work as before:

autopilot/settings/target-altitude-ft

**Comment by Octal450** [comment]
Nope
/fdm/jsbsim/autoflight/pitch/alt/target

Josh

**Comment by NikolaiVChr** [comment]
feet?

**Comment by Octal450** [comment]
Ja, correct.

**Comment by NikolaiVChr** [comment]
Alright missing:
- Make property that can in some cases turn off the SPAK/ATT/ALT pushbuttons light
- Something more. I forgot what it was. Will think.

**Comment by Octal450** [comment]
👌

**Comment by NikolaiVChr** [comment]
Am going to Make those properties now, will do merge request on your github when done I think.

**Comment by NikolaiVChr** [comment]
Thanks for being patient.

**Comment by NikolaiVChr** [comment]
Seems they dont need special properties, just use there, if the property is 1 then turn off the corresponding pushbutton.

systems/indicators/flightstick-secondary
systems/indicators/auto-attitude-secondary
systems/indicators/auto-altitude-secondary

**Comment by NikolaiVChr** [comment]
Okay after some thinking, I have come to the conclusion that the A/P mode is not downgraded when these properties tell the lights to go out.

Reason is simple, these properties depend on the mode, so it only lits up the failure light for example for ATT is A/P is in ATT mode. So when ATT failure comes on if it also triggers a downgrade then the failure light would go out immediatly, and the pilot would never know that something is wrong, beside from A/P being silent downgraded.

This is what I think:
The pushbuttons stays pushed in when pushed (mechanically). So when pushing in ATT and the light is commanded to go out, the pushbutton stays pushed in, but the light in it goes out, and the A/P is really in a lower mode than its mechanically commanded by the pushbuttons.

Or something like that. Maybe I should ask in Viggen Facebook..

**Comment by NikolaiVChr** [comment]
Question asked. Lets see if we get an answer.

**Comment by Octal450** [comment]
Please let me know what I need to change, and when you have the downgrade properties ready for integration into the mode logic.

Kind Regards,
Josh

**Comment by colingeniet** [comment]
@NikolaiVChr I think your interpretation is correct as far as the A/T is concerned: the AJS SFI states:
> A/T re-engagement after manual or automatic disengagement is done by moving the friction lever up to A/T off, then back down to A/T on.

(Note that the JA english SFI is nowhere near as clear, probably due to poor translation. It mentions 'moving the friction lever up to position A/T on', which is likely an error, up should be off)

This implies that the lever does *not* move up automatically when autothrottle is disengaged. Thus I think that at automatic disengagement, the AFK indicator light goes off, the AFK warning light goes on (blinking or not depending on the disengagement cause). The AFK warning light then goes off when pulling the friction lever up to A/T off.

**Comment by colingeniet** [comment]
For the autopilot, the AJS SFI also has details which are missing in the JA translation.
Different extracts from SFI Kap I Flik 12 Sida 27 section 4.3:
> When the master warning is acknowledged, the [autopilot] warning indicators switch to solid.

Also, at least for the HÅLLFUNK warning light (AJS equivalent of ATT+HÖJD in the JA), and for some of the disengagement reasons (excessive angle, transonic flight):
> After the master warning has been acknowledged, the HÅLLFUNK warning light can be extinguished by pressing any of the buttons SPAK, ATT and HÖJD, or the autopilot quick-disengage button.

**Comment by colingeniet** [comment]
Pushed the new auto-throttle engagement logic:
The auto-throttle lever is never locked/automatically moved. It does not reflect the actual auto-throttle engagement state in case of automatic disengagement (the AFK light is there for that).
Re-engagement requires to cycle through the OFF position.

**Comment by colingeniet** [comment]
I'm not sure under which circumstances it should be possible to toggle the high-alpha light.
According to the JA SFI chap 1 sec 22 par 5.7, the high-alpha *light* can only go on when airborne with landing gear down.

I think it would be reasonable to only allow toggling high-alpha when these conditions are met (and to reset it otherwise). Any thoughts?

**Comment by Octal450** [comment]
Yes, agreed. That is good plan. I can add new logic for it

**Comment by colingeniet** [comment]
Already there, feel free to check it.

Also, I made two small changes to the autothrottle disengagement conditions compared to your version:
- Touchdown disengagement is controlled by the right landing gear
- Disengagement below 495km/h only occurs if speed is reducing (cf. description of associated warning light: 'Speed <495km/h and retarding')

**Comment by colingeniet** [comment]
@Octal450 I have an issue with the way the altitude reference for the altitude hold mode is computed.

According to the manual
> The aircraft is first controlled to [vertical speed] less than 2m/s before the basic altitude hold mode engages (an altitude reference is created)

Currently, the altitude reference is computed as soon as altitude hold is selected, with a prediction function to avoid overshooting the reference altitude. However:
- When engaging at low (say climbing 2m/s) vertical speed, the prediction causes the autopilot to continue stabilize a bit higher than the engagement altitude, whereas I think it should re-descend to engagement altitude.
- When misusing the A/T a bit, it is easy to completely 'break' that prediction by engaging at high vertical speed, which causes to massively overshoot the predicted altitude. This should not occur if reference is only computed when stable.

**Comment by Octal450** [comment]
@colingeniet OK, I will update the logic to have this fixed.

Kind Regards,
Josh
