### ISSUE TITLE
Need help with your knowledge in AC3D-Blender scripts

### ISSUE THREAD

**Issue by Symbian9** [NikolaiVChr/flightgear-saab-ja-37-viggen#8]
I create an issue on
https://github.com/majic79/Blender-AC3D/issues/15

PLEASE, Help configurate and modife your "AC3D-Blender" scripts for use it as import/export scripts for ".DNM" and ".SRF" files, that are YSFlight's 3D formats for aircraft and ground objects.

*.DNM is 3D format very similar to AC3D (that include whole aircraft model with many parts).
*.SRF - is 3D format of surface (for single mesh, like "bolt" of "mechanism"). SRF file structure is a part of DNM file structure.

Here is actual scripts only for  Blender 2.49 and python2.6
https://sourceforge.net/projects/ysfsblender

Or maybe You can help to port actual "ysfsblender" scripts for Blender2.6+?

PS. 
Thank Your for your fork of AC3D-Blender, use it well.

**Comment by NikolaiVChr** [comment]
This is not a Viggen related issue, so closing.
