### ISSUE TITLE
MP sounds

### ISSUE THREAD

**Issue by colingeniet** [NikolaiVChr/flightgear-saab-ja-37-viggen#85]
The file `ja37-mp-sound.xml` has been disabled for a few years (commented out in the models), however there are some MP properties which are only used in it.

What should I do with it ? Remove it entirely or try to keep it updated --- I would rather not keep it around with obsolete code that depends on properties that I removed.

**Comment by NikolaiVChr** [comment]
MP Sound is still not fixed in FG and unlikely to be in near future.

I think remove.

**Comment by colingeniet** [comment]
Ok, thank you
