### ISSUE TITLE
Ripple settings for the AJS

### ISSUE THREAD

**Issue by vanosten** [NikolaiVChr/flightgear-saab-ja-37-viggen#95]
I suggest the following primitive ripple setting for the AJS version:
- Add the switch Strömställare SERIE-IMPULS (cf. page 416 in "Fpl AJS 37 speciell förarinstruktion (SFI) del 1") around the place where currently the "Stall warning" switch is (maybe move that one a bit).
- Implement for the RB04 RB15 that they actually get fired with 2 secs interval if "SERIE" is chosen.
- Make a fake implementation that no matter the setting, always at least one bomb from each rack gets released (like for the ARAK). I might be wrong, but it seems to me that bombing IRL was always a single pass. this way one can fly several passes (unless one choses "SERIE" - se next bullet)
- Make a fake implementation that if the switch is on "SERIE" that there is 0.1 seconds wait between each bomb (normally 4) - i.e. if flying 900 km/h there would be 4*25 m between the bombs if flying level. Ideally the interval could be chosen with the SIKTNINGSVÄLJARE, but that can wait.

**Comment by colingeniet** [comment]
Regarding the M71, they are now dropped in sequence (a bit more than 1s to release everything under normal circumstances).
Correct me if I'm wrong, I think that it is the correct behaviour for the M71, 
and that the SERIE-IMPULS switch has no effect for them? (only for the training bombs)

**Comment by colingeniet** [comment]
Closing because it is included in #140
