### ISSUE TITLE
IFF

### ISSUE THREAD

**Issue by NikolaiVChr** [NikolaiVChr/flightgear-saab-ja-37-viggen#96]
Since we dont have any info on how IFF is displayed, we will have to guesstimate.

How do people suggest it should be displayed on MI/TI.

For example on F16, the radar echoes on radar screen is shortly replaced by numbers that tells which IFF interrogations they have passed. Right now its manual, so have to click a key to display it.

**Comment by Rudolf339** [comment]
Maybe something like make an IFF interrogate key, that interrogates selected contact. This data is kept as long as the target remains in the radar scope. If it's lost, in needs to be re-selected and interrogated again

**Comment by NikolaiVChr** [comment]
Could do something like that, but I would prefer something that interrogated all contacts in radar field.

**Comment by Rudolf339** [comment]
Yeah, that's probably more practical

**Comment by colingeniet** [comment]
I went for:
- Selected target is always interrogated.
- `ctrl-F` interrogates the target under the MI cursor, without locking it (so that it is possible to IFF without lock).
Friendly targets are marked with a big cross on MI and HUD.
