### ISSUE TITLE
Wings appear off in MP

### ISSUE THREAD

**Issue by NikolaiVChr** [NikolaiVChr/flightgear-saab-ja-37-viggen#98]
I don't think the problem is with the Viggen.
It might be due to people flying with FG git next.
Look at these properties, almost all were nil (recorded from 2019.1.2):

![fgfs-20200312212055](https://user-images.githubusercontent.com/3764194/76567967-2ec67080-64b0-11ea-9d46-9668fe454e8f.png)
![fgfs-20200312212050](https://user-images.githubusercontent.com/3764194/76567968-2ff79d80-64b0-11ea-9fa9-72128d32ea55.png)

**Comment by colingeniet** [comment]
First thing: this is because I was doing some testing with the MP protocol, the issue should not occur for anyone else.
The properties should not be nil of course, I am using a recent git version indeed, is there some known issue with that?

**Comment by NikolaiVChr** [comment]
Well RAF1 has same issue and he also uses next.

I think there is bug in next, MP protocol 2.

**Comment by colingeniet** [comment]
Just to check, you mean that the problem exists between two persons who are not me?

**Comment by NikolaiVChr** [comment]
When I look at RAF1's properties over MP his properties are mostly nil also.

**Comment by colingeniet** [comment]
That might be a core issue indeed, I will search if I can find something in flightgear source code.

**Comment by NikolaiVChr** [comment]
Nevermind he uses 2019.1.1, hmm maybe I am wrong, I will do some tests of next.

**Comment by colingeniet** [comment]
I did some tests. This is an incompatibility between 2019.2 and 2019.1 in the MP protocol (precisely generic bool properties from 2019.2 are not received by 2019.1), nothing Viggen specific.

**Comment by NikolaiVChr** [comment]
oh, maybe alert Richard to the issue then, he is the one who did all the bools.
